### ISSUE TITLE
UI Improvement

### ISSUE THREAD

**Issue by nikhil3000** [IOSD/CalculatorHacktober#5]
Divide the UI into three suitable colours.
 1) change the background colour of text view and the area above that to color1
2)background colour of all the numeric buttons to colour 2
3)background colour of all the operator buttons to colour 3

P.S choose colors wisely and also change the font color wherever required.
P.P.S Upload the screenshots while sending the pull request. Also, delete the previous screenshots present in the repository.

**Comment by darelover** [comment]
Added background color and font colors to the layout

**Comment by darelover** [comment]
Also, changed the structure of the layout

**Comment by darelover** [comment]
Screenshots 


![screen shot 2017-10-26 at 16 35 18](https://user-images.githubusercontent.com/25029996/32050163-7ef0e954-ba6d-11e7-8b9e-4b9485990e0f.png)
![screen shot 2017-10-26 at 16 34 29](https://user-images.githubusercontent.com/25029996/32050164-7f1e34ea-ba6d-11e7-8e8b-a6f507d94d25.png)
![screen shot 2017-10-26 at 16 34 00](https://user-images.githubusercontent.com/25029996/32050165-7f4d4faa-ba6d-11e7-84e4-6bfe7a0b8aee.png)
